// <auto-generated />
using System;
using Beetles.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beetles.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260504131615_CreateWalls")]
    partial class CreateWalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beetles.Domain.Entities.Beetle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("RecordedFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_from")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("ColonyId")
                        .HasColumnType("integer")
                        .HasColumnName("colony_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("RecordedTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_to")
                        .HasDefaultValueSql("'infinity'::timestamptz");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to")
                        .HasDefaultValueSql("'infinity'::timestamptz");

                    b.HasKey("Id", "ValidFrom", "RecordedFrom")
                        .HasName("pk_beetles");

                    b.HasIndex("ColonyId")
                        .HasDatabaseName("ix_beetles_colony_id");

                    b.ToTable("beetles", (string)null);
                });

            modelBuilder.Entity("Beetles.Domain.Entities.Colony", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_colonies");

                    b.ToTable("colonies", (string)null);
                });

            modelBuilder.Entity("Beetles.Domain.Entities.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("RecordedFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_from")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("RecordedTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_to")
                        .HasDefaultValueSql("'infinity'::timestamptz");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to")
                        .HasDefaultValueSql("'infinity'::timestamptz");

                    b.HasKey("Id", "ValidFrom", "RecordedFrom")
                        .HasName("pk_walls");

                    b.ToTable("walls", (string)null);
                });

            modelBuilder.Entity("Beetles.Domain.Entities.Beetle", b =>
                {
                    b.HasOne("Beetles.Domain.Entities.Colony", "Colony")
                        .WithMany()
                        .HasForeignKey("ColonyId")
                        .HasConstraintName("fk_beetles_colonies_colony_id");

                    b.Navigation("Colony");
                });
#pragma warning restore 612, 618
        }
    }
}
