// <auto-generated />
using System;
using Beetles.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beetles.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260506083809_CreateWalls")]
    partial class CreateWalls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beetles.Domain.Entities.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("BusinessStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("business_start");

                    b.Property<DateTimeOffset>("BusinessEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("business_end")
                        .HasDefaultValueSql("'infinity'::timestamptz");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("SystemEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("system_end")
                        .HasDefaultValueSql("'infinity'::timestamptz");

                    b.Property<DateTimeOffset>("SystemStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("system_start")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id", "BusinessStart", "BusinessEnd")
                        .HasName("pk_walls");

                    b.ToTable("walls", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
