CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260506083809_CreateWalls') THEN
    CREATE TABLE walls (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        business_start timestamp with time zone NOT NULL,
        business_end timestamp with time zone NOT NULL DEFAULT ('infinity'::timestamptz),
        color text NOT NULL,
        system_start timestamp with time zone NOT NULL DEFAULT (now()),
        system_end timestamp with time zone NOT NULL DEFAULT ('infinity'::timestamptz),
        CONSTRAINT pk_walls PRIMARY KEY (id, business_start, business_end)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260506083809_CreateWalls') THEN

                    CREATE EXTENSION IF NOT EXISTS btree_gist;

                    ALTER TABLE walls
                        ADD COLUMN business_period tstzrange
                        GENERATED ALWAYS AS (tstzrange(business_start, business_end)) STORED;

                    ALTER TABLE walls
                        ADD COLUMN system_period tstzrange
                        GENERATED ALWAYS AS (tstzrange(system_start, system_end)) STORED;

                    ALTER TABLE walls
                        ADD CONSTRAINT no_overlap_walls
                        EXCLUDE USING gist (
                            id WITH =,
                            business_period WITH &&,
                            system_period WITH &&
                        );

                    ALTER TABLE walls
                        ADD COLUMN transaction_id bigint GENERATED ALWAYS AS IDENTITY;
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260506083809_CreateWalls') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260506083809_CreateWalls', '10.0.4');
    END IF;
END $EF$;
COMMIT;

