CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260429093049_CreateBeetles') THEN
    CREATE TABLE beetles (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        CONSTRAINT pk_beetles PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260429093049_CreateBeetles') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260429093049_CreateBeetles', '10.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260429171454_CreateColonies') THEN
    CREATE TABLE colonies (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        CONSTRAINT pk_colonies PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260429171454_CreateColonies') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260429171454_CreateColonies', '10.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260430064705_CreateBeetleColonies') THEN
    CREATE TABLE beetle_colonies (
        beetle_id integer NOT NULL,
        colony_id integer NOT NULL,
        valid_from timestamp with time zone NOT NULL,
        recorded_from timestamp with time zone NOT NULL DEFAULT (now()),
        valid_to timestamp with time zone DEFAULT ('infinity'::timestamptz),
        recorded_to timestamp with time zone NOT NULL DEFAULT ('infinity'::timestamptz),
        CONSTRAINT pk_beetle_colonies PRIMARY KEY (beetle_id, colony_id, valid_from, recorded_from),
        CONSTRAINT fk_beetle_colonies_beetles_beetle_id FOREIGN KEY (beetle_id) REFERENCES beetles (id) ON DELETE CASCADE,
        CONSTRAINT fk_beetle_colonies_colonies_colony_id FOREIGN KEY (colony_id) REFERENCES colonies (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260430064705_CreateBeetleColonies') THEN
    CREATE INDEX ix_beetle_colonies_colony_id ON beetle_colonies (colony_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260430064705_CreateBeetleColonies') THEN

                    CREATE EXTENSION IF NOT EXISTS btree_gist;

                    ALTER TABLE beetle_colonies
                        ADD COLUMN valid_period tstzrange
                        GENERATED ALWAYS AS (tstzrange(valid_from, valid_to)) STORED;

                    ALTER TABLE beetle_colonies
                        ADD COLUMN recorded_period tstzrange
                        GENERATED ALWAYS AS (tstzrange(recorded_from, recorded_to)) STORED;

                    ALTER TABLE beetle_colonies
                        ADD CONSTRAINT no_overlap
                        EXCLUDE USING gist (
                            beetle_id WITH =,
                            colony_id WITH =,
                            valid_period WITH &&,
                            recorded_period WITH &&
                        );
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260430064705_CreateBeetleColonies') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260430064705_CreateBeetleColonies', '10.0.4');
    END IF;
END $EF$;
COMMIT;

