CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260503064402_CreateColonies') THEN
    CREATE TABLE colonies (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        CONSTRAINT pk_colonies PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260503064402_CreateColonies') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260503064402_CreateColonies', '10.0.4');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260503065754_CreateBeetles') THEN
    CREATE TABLE beetles (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        valid_from timestamp with time zone NOT NULL,
        recorded_from timestamp with time zone NOT NULL DEFAULT (now()),
        name text NOT NULL,
        valid_to timestamp with time zone DEFAULT ('infinity'::timestamptz),
        recorded_to timestamp with time zone NOT NULL DEFAULT ('infinity'::timestamptz),
        CONSTRAINT pk_beetles PRIMARY KEY (id, valid_from, recorded_from)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260503065754_CreateBeetles') THEN

                    CREATE EXTENSION IF NOT EXISTS btree_gist;

                    ALTER TABLE beetles
                        ADD COLUMN valid_period tstzrange
                            GENERATED ALWAYS AS (tstzrange(valid_from, valid_to)) STORED;

                    ALTER TABLE beetles
                        ADD COLUMN recorded_period tstzrange
                            GENERATED ALWAYS AS (tstzrange(recorded_from, recorded_to)) STORED;

                    ALTER TABLE beetles
                        ADD CONSTRAINT no_overlap
                            EXCLUDE USING gist (
                                id WITH =,
                                valid_period WITH &&,
                                recorded_period WITH &&
                            );
                
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260503065754_CreateBeetles') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260503065754_CreateBeetles', '10.0.4');
    END IF;
END $EF$;
COMMIT;

